### ISSUE TITLE
I don't see the point of this

### ISSUE THREAD

**Issue by JosephSilber** [captbaritone/hashbin#6]
Avoiding takedown notices is only an accomplishment if the linker can't get a takedown notice.

The way this works, all the data will reside on the site linking to you (albeit encoded).

To follow your example, it's as if I would post a Word document on my site with some private information. Even though it can't be viewed directly on my site, I'm still hosting infringing content.

**Comment by captbaritone** [comment]
You are absolutely correct.

This does not prevent **content** from being taken down, it just shifts the responsibility away from the paste bin.

That being said, I think it still provides some interesting value. With a traditional paste bin, there is a single point of failure. Many sites may be linking to a paste, but if somebody can get the paste taken down, the content is gone. With this model, the people who want the content taken down would have to go after ALL the sites that link to it, or maybe even a link shortening service who had shortened the link (and in the process unknowingly taken on the responsibility of hosting the content).

Links can propagate very quickly. For example, if Google indexes your paste, you may need to send a takedown notice to Google... and Bing... and Yahoo... (ect).

More than anything this is intended as a thought experiment.
- What happens when we make any site that will let you post a link, including url shorteners, into an arbitrary data store?
- Is a site that hosts a link responsible for the content of that link?

**Comment by JosephSilber** [comment]
> I think it still provides some interesting value. [...] With this model, the people who want the content taken down would have to go after ALL the sites that link to it

Since this shifts the responsibility to the sites linking to you, they could just as easily have the text directly on their site.

What do they gain by encoding it and linking to your site like that?

**Comment by captbaritone** [comment]
There are many sites that will let users post a link, that will not let users post arbitrary data.

For example, a common way to leak information is to create a paste bin and then link to that paste bin from Twitter. From there the link propagates to other blogs or news outlets.

With HashBin, Twitter's URL shortener will host your content for you.

**Comment by captbaritone** [comment]
Closing this issue, but I'll gladly reopen if anyone has any other questions.

**Comment by JosephSilber** [comment]
Just to add in case it wasn't clear: I didn't come here to hate. Was genuinely pointing out that I don't understand it.

Interesting thought nonetheless :smile:

**Comment by captbaritone** [comment]
No worries! In fact, thanks for asking me to clarify rather than simply dismissing it.

I know it's a rather subtle point, and I may not have done the best job of explaining it, so having a chance to discuss it was helpful to me.

Cheers :smile:
